# Generated by Django 3.0.8 on 2020-07-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='create_date',
            field=models.DateField(default="2020-02-02", verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
