# Generated by Django 3.0.8 on 2020-07-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_news_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
