# Generated by Django 3.0.8 on 2020-07-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200727_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
