# Generated by Django 3.0.8 on 2020-07-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(default=0, upload_to='detais'),
            preserve_default=False,
        ),
    ]
