# Generated by Django 3.0.8 on 2020-08-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('editor', 'editor')], default='user', max_length=255),
        ),
    ]
