# Generated by Django 3.0.8 on 2020-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activate_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('admin', 'Админ'), ('user', 'Юзер'), ('editor', 'Едитор')], default='user', max_length=255),
        ),
    ]
